export interface Neighborhood {
  slug: string;
  name: string;
  type: 'neighborhood' | 'rv-park' | 'family-park';
  city: string;
  description: string;
  audience: string;
  /** Unique per-page hero paragraph — written individually, not templated. */
  intro: string;
  /** Unique per-page "cleaning in this community" paragraph. */
  careNotes: string;
  latitude?: number;
  longitude?: number;
}

export const NEIGHBORHOODS: Neighborhood[] = [
  // Neighborhoods
  { slug: 'araby', name: 'Araby', type: 'neighborhood', city: 'Yuma', description: 'Established neighborhood in Yuma.', audience: 'Families and professionals in Yuma.',
    intro: 'Araby is one of the areas our crews visit most, and the homes here follow a pattern we know well: established houses where dust has had years to settle into blinds, vents, and the tops of ceiling fans. A first deep clean in an older Yuma home usually surprises people — not because the home was dirty, but because desert dust accumulates in places weekly tidying never reaches.',
    careNotes: 'For Araby homes we typically recommend starting with a deep clean to reset baseboards, vents, and grout, then holding it with bi-weekly recurring service. Established homes with original tile benefit most from regular grout attention before Yuma\'s hard water discolors it permanently.',
    latitude: 32.69, longitude: -114.63 },
  { slug: 'barkley-ranch', name: 'Barkley Ranch', type: 'neighborhood', city: 'Yuma', description: 'Suburban neighborhood development.', audience: 'Families seeking suburban living.',
    intro: 'Newer suburban builds like those in Barkley Ranch clean up differently than older Yuma housing stock — modern finishes, bigger windows, and open floor plans mean more glass and more visible floor. What shows first in these homes is not grime but film: hard water spotting on shower glass and a fine dust haze on dark floors.',
    careNotes: 'In Barkley Ranch we spend proportionally more time on floors and glass than in older neighborhoods. Bi-weekly service keeps dark tile and plank flooring from showing the dust film that builds between visits, and consistent shower squeegee-downs stop mineral spotting before it etches.',
    latitude: 32.71, longitude: -114.59 },
  { slug: 'cielo-verde', name: 'Cielo Verde', type: 'neighborhood', city: 'Yuma', description: 'Planned community in Yuma.', audience: 'Residents seeking planned community amenities.',
    intro: 'Planned communities like Cielo Verde tend to have consistent floor plans, which works in your favor: once our cleaner learns your layout, every visit runs the same route with nothing missed. That consistency is exactly why we assign the same cleaner to your home every time.',
    careNotes: 'Cielo Verde clients most often book bi-weekly recurring service with a seasonal deep clean before the holidays. Homes with covered patios here also ask us about door-track and sliding-glass detail work — desert grit collects in those tracks faster than anywhere else in the house.',
    latitude: 32.68, longitude: -114.60 },
  { slug: 'college-park', name: 'College Park', type: 'neighborhood', city: 'Yuma', description: 'Neighborhood near Yuma area.', audience: 'College students and young professionals.',
    intro: 'College Park sees more rental turnover than most Yuma neighborhoods, and that shapes the cleaning work we do here: move-out cleans that need to pass a landlord walkthrough, and move-in cleans for people who want a fresh start before unpacking a single box.',
    careNotes: 'Our move-out service in College Park covers the items deposits actually get docked for — inside the oven and refrigerator, cabinet interiors, window tracks, and bathroom mineral buildup. Renters here often split the cost of a move-out clean against what they would lose from a deposit deduction.',
    latitude: 32.73, longitude: -114.63 },
  { slug: 'country-roads-neighborhood', name: 'Country Roads', type: 'neighborhood', city: 'Yuma', description: 'Suburban development community.', audience: 'Families seeking suburban lifestyle.',
    intro: 'The Country Roads area mixes full-time family households with seasonal residents, which means we do two very different kinds of work here: steady recurring cleans through the school year, and open-up or close-down cleans when seasonal owners arrive in fall or head out in spring.',
    careNotes: 'If you are seasonal, book your arrival clean a few days before you get to town — a home that sat closed through a Yuma summer needs vents, fans, and every horizontal surface reset before it feels right. Full-timers here mostly run bi-weekly service with a monsoon-season deep clean.',
    latitude: 32.70, longitude: -114.60 },
  { slug: 'cresta-gila-estates', name: 'Cresta Gila Estates', type: 'neighborhood', city: 'Yuma', description: 'Residential estates community.', audience: 'Homeowners seeking quality estates.',
    intro: 'Larger estate-style homes like those in Cresta Gila Estates change the cleaning math: more square footage, more bathrooms, and more glass mean a quick surface pass never quite keeps up. Our flat-rate quote is built from your actual bedroom and bathroom count, so the price reflects your home — and then never changes visit to visit.',
    careNotes: 'For bigger homes in Cresta Gila Estates we often split deep-clean work across two visits — wet areas first, living areas second — so no single visit disrupts your whole day. Multiple bathrooms in hard-water country also mean shower glass treatment matters more here than in smaller homes.',
    latitude: 32.67, longitude: -114.62 },
  { slug: 'desert-ridge', name: 'Desert Ridge', type: 'neighborhood', city: 'Yuma', description: 'Desert-view residential community.', audience: 'Families seeking desert living.',
    intro: 'Homes in Desert Ridge sit close to open desert, and open desert means airborne dust with a short commute to your windowsills. Residents here notice the difference between cleaning weeks and skipped weeks faster than almost anywhere else we service.',
    careNotes: 'Desert Ridge homes do best on a bi-weekly schedule at minimum, with extra attention to window tracks, entryway floors, and return-air grilles. After a dust storm, we recommend adding a one-time refresh — haboob dust keeps settling for days after the sky clears.',
    latitude: 32.69, longitude: -114.61 },
  { slug: 'foothills-neighborhood', name: 'Foothills', type: 'neighborhood', city: 'Yuma', description: 'Foothills area residential community.', audience: 'Residents seeking elevated living.',
    intro: 'The Foothills is one of the largest service areas we cover, with everything from year-round family homes to winter residences that sit empty half the year. Both get the same crew and the same checklist — what changes is the rhythm of the visits.',
    careNotes: 'Year-round Foothills households usually settle into bi-weekly service. Winter residents book differently: an arrival deep clean in October or November, regular service through the season, and a close-down clean in spring so the house is not marinating in dust all summer.',
    latitude: 32.68, longitude: -114.62 },
  { slug: 'las-barrancas', name: 'Las Barrancas', type: 'neighborhood', city: 'Yuma', description: 'Established community neighborhood.', audience: 'Diverse families and professionals.',
    intro: 'Las Barrancas households tend to be busy ones — dual-income families and working professionals who want to come home to a finished house, not a to-do list. Most of our clients here started with a one-time deep clean and converted to recurring service within the month.',
    careNotes: 'The most popular booking in Las Barrancas is bi-weekly recurring service covering kitchens, bathrooms, floors, and dusting throughout. Families with pets here add our pet-hair floor detail — Yuma dust plus pet hair forms a felt-like layer under furniture that standard vacuuming skips.',
    latitude: 32.72, longitude: -114.64 },
  { slug: 'mesa-del-sol-neighborhood', name: 'Mesa Del Sol', type: 'neighborhood', city: 'Yuma', description: 'Upscale foothills development.', audience: 'Affluent families seeking premium living.',
    intro: 'Mesa Del Sol homes tend toward larger footprints and finish materials that reward careful handling — natural stone, custom cabinetry, oversized showers. Our crews clean to the material, not just the room: stone gets neutral cleaners, stainless gets polished with the grain, and glass gets finished streak-free.',
    careNotes: 'In Mesa Del Sol we quote by home size and configuration, and the flat rate holds visit after visit. Owners here most often combine bi-weekly service with a quarterly deep clean covering baseboards, vents, blinds, and the grout and shower-glass detail that protects stone and tile from hard-water damage.',
    latitude: 32.68, longitude: -114.62 },
  { slug: 'ocotillo', name: 'Ocotillo', type: 'neighborhood', city: 'Yuma', description: 'Desert-themed residential area.', audience: 'Desert lifestyle enthusiasts.',
    intro: 'Desert landscaping is beautiful and low-water, but Ocotillo homeowners know its trade-off: gravel yards and open lots feed a constant trickle of grit through every door. The cleaning battle here is fought at thresholds, entry mats, and the first ten feet of flooring inside each door.',
    careNotes: 'We hit entry zones hard on every Ocotillo visit — vacuuming before mopping so grit never gets pushed across tile, and detailing door tracks where sand piles up. Homes here also benefit from quarterly vent and fan attention, since dust rides the AC system year-round.',
    latitude: 32.66, longitude: -114.60 },
  { slug: 'old-world-village', name: 'Old World Village', type: 'neighborhood', city: 'Yuma', description: 'European-inspired community.', audience: 'Residents seeking unique architecture.',
    intro: 'Distinctive architecture means distinctive cleaning: Old World Village homes tend to have more textured surfaces, niches, and decorative trim than a standard Yuma tract home, and every ledge is a place desert dust wants to live.',
    careNotes: 'Our cleaners work detail-first in Old World Village — trim, ledges, and light fixtures get dusted top-down before floors are touched. It takes a more methodical pass than a flat-walled modern home, and the flat-rate quote accounts for that up front.',
    latitude: 32.70, longitude: -114.61 },
  { slug: 'parkway-place', name: 'Parkway Place', type: 'neighborhood', city: 'Yuma', description: 'Urban residential neighborhood.', audience: 'Urban dwellers and professionals.',
    intro: 'Parkway Place sits close to the busier corridors of town, and proximity to traffic means finer, darker dust than the desert variety — the kind that shows on white windowsills and settles into window screens.',
    careNotes: 'For Parkway Place homes we recommend adding screen and sill detail to at least one clean per quarter. Day-to-day, most clients here run standard bi-weekly service; the road-dust film builds slowly enough that a consistent schedule stays ahead of it.',
    latitude: 32.74, longitude: -114.63 },
  { slug: 'picacho-village', name: 'Picacho Village', type: 'neighborhood', city: 'Yuma', description: 'Village-style residential community.', audience: 'Families seeking village ambiance.',
    intro: 'Smaller-lot living like Picacho Village keeps homes close together and yards manageable — and from a cleaning standpoint, compact homes are where flat-rate pricing shines. A modest floor plan gets a genuinely thorough clean in a single visit, every visit.',
    careNotes: 'Most Picacho Village clients book monthly or bi-weekly maintenance cleans covering the full home each time rather than rotating rooms. With less square footage to cover, our cleaners can afford detail time on the kitchen and bathrooms that bigger homes trade away.',
    latitude: 32.65, longitude: -114.61 },
  { slug: 'sunset-mesa', name: 'Sunset Mesa', type: 'neighborhood', city: 'Yuma', description: 'Mesa-view residential development.', audience: 'Nature-loving homeowners.',
    intro: 'Sunset Mesa homes catch the west light, and west light is unforgiving — it turns every streak on a window and every film of dust on a dark counter into a spotlight moment by late afternoon.',
    careNotes: 'Glass and reflective surfaces get priority in Sunset Mesa. We finish windows and mirrors streak-free and wipe counters with microfiber rather than sponges, because in this light the difference between clean and almost-clean is visible from across the room.',
    latitude: 32.67, longitude: -114.59 },
  { slug: 'vista-del-valle', name: 'Vista del Valle', type: 'neighborhood', city: 'Yuma', description: 'Valley-view residential area.', audience: 'Families seeking valley views.',
    intro: 'Vista del Valle households are mostly settled families, and family homes generate a specific kind of cleaning load: high-touch surfaces, busy kitchens, and bathrooms that work hard all week. Our job here is less about rescuing a home and more about keeping a well-used one comfortable.',
    careNotes: 'The standard Vista del Valle booking is bi-weekly service with kitchen and bathroom focus, and many families add inside-the-microwave and cabinet-front wipe-downs as standing requests. Standing requests stick, because the same cleaner returns every visit.',
    latitude: 32.71, longitude: -114.62 },
  { slug: 'yuma-foothills', name: 'Yuma Foothills', type: 'neighborhood', city: 'Yuma', description: 'Foothills residential community.', audience: 'Upscale homeowners.',
    intro: 'Out in the Yuma Foothills, homes sit on bigger lots with more open desert between neighbors — which means more wind exposure and a faster dust cycle than in-town properties. It is common for Foothills clients to move from monthly to bi-weekly service after their first summer.',
    careNotes: 'We treat dust control as the core job in the Yuma Foothills: ceiling fans, window tracks, blinds, and return-air grilles are on the checklist every visit, not just during deep cleans. After monsoon storms roll through, a between-visit refresh is worth booking.',
    latitude: 32.68, longitude: -114.61 },
  { slug: 'east-yuma', name: 'East Yuma', type: 'neighborhood', city: 'Yuma', description: 'Eastern Yuma residential area.', audience: 'Convenient location seekers.',
    intro: 'East Yuma covers a broad stretch of housing, from older established streets to newer builds, and our crews service all of it on regular routes — which often means same-week availability when you need a first clean scheduled fast.',
    careNotes: 'Because we run frequent routes through East Yuma, recurring clients here get reliable standing time slots and quick rescheduling when life intervenes. New clients typically start with a deep clean, then choose weekly, bi-weekly, or monthly from there.',
    latitude: 32.73, longitude: -114.55 },
  { slug: 'fairgrounds-area', name: 'Fairgrounds Area', type: 'neighborhood', city: 'Yuma', description: 'Near fairgrounds community.', audience: 'Event-minded residents.',
    intro: 'Living near the fairgrounds means event weekends bring traffic, parking, and a noticeable bump in dust and litter drift through the neighborhood. Homes here get more use too — residents host friends and family when something is on.',
    careNotes: 'Fairgrounds Area clients like scheduling cleans to land just before hosting weekends, and we accommodate those one-off timing shifts for recurring customers. A post-event refresh focused on floors and bathrooms is the other common request.',
    latitude: 32.71, longitude: -114.66 },
  { slug: 'riverfront-neighborhood', name: 'Riverfront', type: 'neighborhood', city: 'Yuma', description: 'Colorado River-area community.', audience: 'Waterfront living seekers.',
    intro: 'Homes near the Colorado River corridor deal with a different microclimate than the rest of Yuma — slightly more humidity, more insects, and greenery that most of the desert never sees. The cleaning profile shifts with it.',
    careNotes: 'Riverfront-area cleans include closer attention to window corners and door frames where insects collect, and to bathroom ventilation where the extra humidity lingers. Dust still rules here — it is still Yuma — but it shares the checklist.',
    latitude: 32.74, longitude: -114.68 },
  { slug: 'saguaro-estates', name: 'Saguaro Estates', type: 'neighborhood', city: 'Yuma', description: 'Saguaro cactus estates.', audience: 'Desert plant enthusiasts.',
    intro: 'Saguaro Estates yards showcase desert plantings, and desert-landscaped lots share one indoor consequence: nothing between the soil and your door slows the dust down. Homes here run dustier than turf-lawn streets and residents generally know it.',
    careNotes: 'The Saguaro Estates routine leans on high-frequency dust control — fans, sills, blinds, and electronics surfaces every visit, not rotationally. Bi-weekly service is the practical floor here; monthly tends to disappoint by week three.',
    latitude: 32.68, longitude: -114.62 },
  { slug: 'south-yuma', name: 'South Yuma', type: 'neighborhood', city: 'Yuma', description: 'Southern Yuma residential area.', audience: 'South-side residents.',
    intro: 'South Yuma is working-family territory, and the cleaning we do here is practical: houses that need to function on school-and-shift schedules, cleaned by a service that shows up when it says it will and charges what it quoted.',
    careNotes: 'Our South Yuma clients mostly run bi-weekly or monthly service, booked into standing slots that survive schedule chaos. The flat rate is the same every visit, and the 24-hour re-clean guarantee backs every one of them.',
    latitude: 32.65, longitude: -114.63 },
  { slug: 'west-yuma', name: 'West Yuma', type: 'neighborhood', city: 'Yuma', description: 'Western Yuma residential area.', audience: 'West-side residents.',
    intro: 'West Yuma runs toward the river and the older bones of the city, with housing that spans decades of styles on adjacent blocks. Our crews clean all of it, and the variety is exactly why we quote homes individually instead of by zip code.',
    careNotes: 'A West Yuma quote reflects your actual home — size, bathrooms, flooring, condition — and then locks in flat. Older properties here often start with a deep clean; newer ones frequently jump straight to recurring service.',
    latitude: 32.69, longitude: -114.67 },

  // RV Parks & Resorts
  { slug: 'adobe-village-rv-park', name: 'Adobe Village RV Park', type: 'rv-park', city: 'Yuma', description: 'Adobe-style RV community.', audience: '55+ retirees and RV enthusiasts.',
    intro: 'Adobe Village RV Park residents tend to be particular about who comes into their homes, and we respect that: you get one assigned cleaner, not a rotating cast of strangers. After a couple of visits they know your park model as well as you do.',
    careNotes: 'Most of our work at Adobe Village runs October through April, matching the season most residents keep. A compact home cleans fast, which is why our flat rate here sits well below what a full-size house costs.',
    latitude: 32.68, longitude: -114.61 },
  { slug: 'arizona-west-rv-park', name: 'Arizona West RV Park', type: 'rv-park', city: 'Yuma', description: '55+ retirement and senior RV resort with full amenities.', audience: '55+ retirees and seasonal snowbirds.',
    intro: 'Snowbirds heading back to Arizona West RV Park each fall face the same first chore: a home that has been shut tight since spring. We take that job off the list — book an open-up clean for the day before you roll in and walk into a place that already smells like someone lives there.',
    careNotes: 'An open-up visit at Arizona West means every surface wiped, fans and vents de-dusted, the fridge and bathroom reset, and floors done last so nothing lands on them afterward. Plenty of clients then keep us on through April for regular touch-ups.',
    latitude: 32.66, longitude: -114.54 },
  { slug: 'araby-acres-rv-resort', name: 'Araby Acres RV Resort', type: 'rv-park', city: 'Yuma', description: 'Spacious acres RV resort.', audience: 'Full-hookup RV travelers.',
    intro: 'Pricing at Araby Acres RV Resort is refreshingly simple for us to quote, because the homes are compact and predictable in scope. Smaller square footage means a smaller flat rate — you are never paying big-house prices for a park-model-sized job.',
    careNotes: 'We clean everything at Araby Acres from travel trailers parked for the winter to park models that stay put year to year. Whatever you live in, the rate is fixed up front and stays fixed for every visit after.',
    latitude: 32.69, longitude: -114.63 },
  { slug: 'bonita-mesa-rv-resort', name: 'Bonita Mesa RV Resort', type: 'rv-park', city: 'Yuma', description: 'Beautiful mesa RV resort.', audience: 'Scenic view seekers.',
    intro: 'When spring comes and Bonita Mesa RV Resort starts emptying out, our close-down cleans get busy. Leaving a home spotless before you lock it for the summer matters more than people expect — grime that sits through five months of desert heat sets in ways it never would in a lived-in house.',
    careNotes: 'A departure clean at Bonita Mesa clears the kitchen of anything that could attract pests, wipes down wet areas so mineral deposits do not bake in, and leaves the whole place ready to reopen with nothing worse than a season of dust. Come October, the reopening is a far smaller job because of it.',
    latitude: 32.67, longitude: -114.61 },
  { slug: 'cactus-gardens-rv-resort', name: 'Cactus Gardens RV Resort', type: 'rv-park', city: 'Yuma', description: 'Cactus-garden RV retreat.', audience: 'Desert landscape lovers.',
    intro: 'Desert dust does not knock — it slips in around door seals, window frames, and roof vents, and in a small home it shows up fast. Residents at Cactus Gardens RV Resort see a fine grey layer on dark countertops within days of a good wind, no matter how tight the place is buttoned up.',
    careNotes: 'Our approach at Cactus Gardens is frequency over firepower: shorter, regular visits keep the dust from ever building into the kind of coating that takes a deep clean to remove. Window tracks and screen-door channels get attention every time, since that is where the grit stages its next entrance.',
    latitude: 32.68, longitude: -114.60 },
  { slug: 'capri-rv-resort', name: 'Capri RV Resort', type: 'rv-park', city: 'Yuma', description: 'Mediterranean-style RV resort.', audience: 'Luxury RV seekers.',
    intro: 'Compact bathrooms concentrate Yuma\'s hard-water problem: one small shower enclosure, one sink, one faucet set, all spotting white within a week of neglect. At Capri RV Resort that mineral film is the number-one complaint we hear on first visits.',
    careNotes: 'We give Capri bathrooms a proper hard-water detail — glass, chrome, and tile treated until the spotting is gone, not just wiped shinier. Kept on a recurring schedule afterward, the buildup never gets a foothold again.',
    latitude: 32.69, longitude: -114.62 },
  { slug: 'caravan-oasis-rv-resort', name: 'Caravan Oasis RV Resort', type: 'rv-park', city: 'Yuma', description: 'Oasis-themed RV community.', audience: 'Desert travelers.',
    intro: 'The middle of the season is where recurring service earns its keep at Caravan Oasis RV Resort. You came to Yuma for winter sunshine, potlucks, and day trips — not to spend your good months scrubbing a shower stall.',
    careNotes: 'Caravan Oasis clients mostly run an every-other-week rotation from the time they arrive until the day they pull out. Because the homes are modest in size, each visit is quick, affordable, and easy to slot around whatever the park has going on that day.',
    latitude: 32.71, longitude: -114.61 },
  { slug: 'carefree-village-resort', name: 'Carefree Village Resort', type: 'rv-park', city: 'Yuma', description: 'Carefree RV lifestyle.', audience: 'Retired travelers.',
    intro: 'Grandkids visiting for a long weekend? Adult children flying in over the holidays? Carefree Village Resort residents call us for exactly those moments — a guest-ready clean a day or two before company lands, so the house looks its best without anyone breaking a sweat.',
    careNotes: 'A pre-visit clean at Carefree Village hits the things guests actually notice: the bathroom top to bottom, the guest sleeping area, floors, and every glass surface. Book it as a one-off or tack it onto your regular schedule whenever family season rolls around.',
    latitude: 32.70, longitude: -114.62 },
  { slug: 'cocopah-bend-rv-golf', name: 'Cocopah Bend RV & Golf Resort', type: 'rv-park', city: 'Yuma', description: '55+ golf RV resort.', audience: 'Golfing retirees.',
    intro: 'Nobody at a golf resort wants to trade a morning tee time for a mop. Our Cocopah Bend RV & Golf Resort clients schedule us for the hours they are out on the course, and come home to a finished house instead of a chore list.',
    careNotes: 'Golf communities keep full social calendars, so at Cocopah Bend we work around standing games, league days, and clubhouse events without you needing to be home. Same cleaner each time means the routine holds even when your schedule does not.',
    latitude: 32.67, longitude: -114.59 },
  { slug: 'country-roads', name: 'Country Roads RV Village', type: 'rv-park', city: 'Yuma', description: 'Large RV park serving active adults and seasonal snowbirds.', audience: '55+ active adults and seasonal snowbirds.',
    intro: 'A park the size of Country Roads gives us a steady rhythm: arrival cleans stacking up through October and November, regular service all winter, then a wave of lock-up cleans as the exodus starts in spring. We have crews in this park often enough that fitting your dates in is rarely a problem.',
    careNotes: 'Whichever end of the season you are booking at Country Roads, the earlier you claim a date the better — the same few weeks are busy for everyone. Mid-winter, recurring slots are flexible and the flat rate for a park-sized home stays easy on a fixed income.',
    latitude: 32.70, longitude: -114.60 },
  { slug: 'del-pueblo-rv-resort', name: 'Del Pueblo RV Resort', type: 'rv-park', city: 'Yuma', description: '55+ community with RV and Park Model home options.', audience: '55+ retirees choosing between RV and park model living.',
    intro: 'Del Pueblo RV Resort mixes RV sites with park model homes, and we clean both — though the jobs differ more than you might think. A park model is a small house with real cabinetry, a full bathroom, and window coverings that trap dust; an RV interior is tighter quarters with more built-ins per square foot.',
    careNotes: 'For Del Pueblo park models we bring the full residential checklist scaled to the footprint; for RV interiors we adapt to the layout in front of us. Either way you are quoted once, flat, before we start.',
    latitude: 32.60, longitude: -114.62 },
  { slug: 'desert-holiday-rv-resort', name: 'Desert Holiday RV Resort', type: 'rv-park', city: 'Yuma', description: 'Holiday-themed desert resort.', audience: 'Vacation-minded RVers.',
    intro: 'Winter in Yuma is the season people at Desert Holiday RV Resort wait for all year, and Thanksgiving through New Year\'s is its busiest stretch. That is precisely when our phone rings most here — homes getting spruced up before dinners, visitors, and park festivities.',
    careNotes: 'If you want a holiday-week slot at Desert Holiday, reserve it in early November; those dates go first every year. The rest of the season we keep a lighter recurring cadence that holds the shine between celebrations.',
    latitude: 32.68, longitude: -114.62 },
  { slug: 'desert-paradise-rv-resort', name: 'Desert Paradise RV Resort', type: 'rv-park', city: 'Yuma', description: 'Paradise RV living.', audience: 'Winter escape seekers.',
    intro: 'Five months of Yuma summer is hard on an empty home. By the time Desert Paradise RV Resort owners return in fall, heat has cooked odors into soft surfaces and a season of fine dust has drifted through every gap — even in a home that was sealed carefully.',
    careNotes: 'The post-summer deep clean we do at Desert Paradise is the most thorough visit of the year: ceiling fans, vent covers, blinds, and cabinet tops all get cleared before we ever touch the floors. Once that reset is done, keeping the home nice through winter is light work.',
    latitude: 32.70, longitude: -114.60 },
  { slug: 'foothills-village-rv-resort', name: 'Foothills Village RV Resort', type: 'rv-park', city: 'Yuma', description: 'Village-style foothills RV resort.', audience: 'Scenic RV enthusiasts.',
    intro: 'Some Foothills Village RV Resort owners come and go several times a season rather than staying put from fall to spring. Homes that sit empty for a few weeks at a stretch collect dust in a way continuously lived-in places never do — nothing disturbs it, so it just keeps layering.',
    careNotes: 'For in-and-out owners at Foothills Village we offer refresh cleans timed to your return dates: a focused visit that clears the accumulation and restocks the basics of a livable house. Tell us when you land and the place will be ready before your bags are.',
    latitude: 32.68, longitude: -114.62 },
  { slug: 'fortuna-de-oro', name: 'Fortuna de Oro', type: 'rv-park', city: 'Yuma', description: '1,200-site 55+ golf RV park and retirement community in the Yuma Foothills.', audience: '55+ golfers and active adults.',
    intro: 'With 1,200 sites, Fortuna de Oro is effectively a small town, and we treat it like a regular stop rather than a special trip. That scale works in your favor: our crews are nearby often, so both scheduled service and short-notice requests are easier to accommodate here than almost anywhere else we go.',
    careNotes: 'Between the course, the clubs, and everything else on the Fortuna de Oro calendar, most residents would rather be anywhere but home with a vacuum. Hand us a key arrangement you are comfortable with and the house gets done while you are out living your winter.',
    latitude: 32.68, longitude: -114.41 },
  { slug: 'friendly-acres-rv-park', name: 'Friendly Acres RV Park', type: 'rv-park', city: 'Yuma', description: 'Multi-use RV and mobile home facility since 1971.', audience: 'Families and RV enthusiasts.',
    intro: 'Friendly Acres RV Park has been operating since 1971, and a community that established holds a real mix of residents — long-timers in mobile homes alongside RVers passing a winter. We match the service to the household instead of assuming everyone here wants the same thing.',
    careNotes: 'Year-round Friendly Acres residents usually land on a steady monthly or bi-weekly plan, while wintering RVers book by the season. Older mobile homes get gentler products on original fixtures and paneling, because aggressive chemicals do more harm than good on aged finishes.',
    latitude: 32.71, longitude: -114.68 },
  { slug: 'gila-mountain-rv-park', name: 'Gila Mountain RV Park', type: 'rv-park', city: 'Yuma', description: 'Mountain-view RV park.', audience: 'Nature-loving RVers.',
    intro: 'Here is the honest math on cleaning at Gila Mountain RV Park: a park model or RV interior is a fraction of the square footage of a stick-built house, so it costs a fraction to keep clean. People who assumed professional cleaning was a luxury are often surprised by what a small-home quote actually comes to.',
    careNotes: 'Every Gila Mountain quote is flat-rate and sized to the actual home — no hourly meter running, no surprise add-ons at the door. Small space, small price, same standard of work we bring to a five-bedroom.',
    latitude: 32.66, longitude: -114.62 },
  { slug: 'hidden-cove-rv-park', name: 'Hidden Cove RV Park', type: 'rv-park', city: 'Yuma', description: 'Secluded cove RV park.', audience: 'Privacy-seeking RVers.',
    intro: 'People choose Hidden Cove RV Park partly for the quiet, and inviting a service into a private home should not undo that. Our answer is consistency: the cleaner who does your first visit does your tenth, so trust only has to be built once.',
    careNotes: 'At Hidden Cove we keep arrangements simple and low-traffic — one familiar face, a standing appointment window, and no crew rotations through your space. If you prefer to be home while we work, that is always fine with us.',
    latitude: 32.69, longitude: -114.61 },
  { slug: 'kofa-koop', name: 'Kofa Ko Op', type: 'rv-park', city: 'Yuma', description: 'Kofa cooperative RV park.', audience: 'Co-op community members.',
    intro: 'Cooperative parks run on word of mouth, and Kofa Ko Op is no exception — when members own the place together, recommendations travel fast and a service either earns its reputation or loses it. Most of our clients here came from a neighbor mentioning us at a meeting or over coffee.',
    careNotes: 'Owner-members at Kofa Ko Op tend to invest in their units the way any homeowner does, and regular professional cleaning protects that investment between seasons. We are glad to coordinate multiple neighboring units on the same day, which keeps the trip efficient for everyone.',
    latitude: 32.65, longitude: -114.58 },
  { slug: 'mesa-verde-rv-resort', name: 'Mesa Verde RV Resort', type: 'rv-park', city: 'Yuma', description: 'Green mesa RV resort.', audience: 'Eco-conscious RVers.',
    intro: 'A pattern we see at Mesa Verde RV Resort: someone books a single clean in November "just to try it," and by December they are on the calendar every other week. Once the house has been professionally reset, most people decide the winter is too short to give any of it back to housework.',
    careNotes: 'Recurring visits at Mesa Verde stay short because nothing ever gets ahead of us — kitchen, bath, floors, and dusting on a loop that keeps the whole home at the level of that first clean. Pause the schedule any time your plans change.',
    latitude: 32.67, longitude: -114.61 },
  { slug: 'og-rv-resort', name: 'OG RV Resort', type: 'rv-park', city: 'Yuma', description: 'Original RV resort.', audience: 'Classic RV travelers.',
    intro: 'The first clean of the winter sets the tone for the whole stay, which is why OG RV Resort arrivals are some of our favorite jobs. There is a real difference between unpacking into a stale, dusty unit and unpacking into one that was made ready the day before.',
    careNotes: 'Give us your arrival date at OG RV Resort and we will have the unit aired out in spirit if not in fact — surfaces wiped, bedroom and bath reset, floors finished, ready for you to simply move back into your winter life. Many owners pair it with a matching clean on the way out in spring.',
    latitude: 32.68, longitude: -114.61 },
  { slug: 'orchard-gardens', name: 'Orchard Gardens', type: 'rv-park', city: 'Yuma', description: '126-unit shareholder-owned 55+ gated cooperative.', audience: '55+ cooperative members and retirees.',
    intro: 'Orchard Gardens is a 126-unit shareholder-owned cooperative, which changes the character of the place: these are owners with a stake in the community, not tenants passing through. Homes held that way get cared for that way, and hiring cleaning help is part of the same instinct.',
    careNotes: 'Because Orchard Gardens is gated, we sort out access with each client ahead of the first visit and keep the arrangement consistent after that. Shareholders who winter elsewhere sometimes have us check in on and freshen the unit before they return.',
    latitude: 32.73, longitude: -114.61 },
  { slug: 'rancho-rialto', name: 'Rancho Rialto', type: 'rv-park', city: 'Yuma', description: '55+ pet-friendly RV resort with walled and gated security.', audience: 'Pet-friendly 55+ retirees and active adults.',
    intro: 'A pet-friendly park means pet-hair cleaning, and Rancho Rialto keeps us practiced at it. In a compact home, one dog\'s worth of hair and dander concentrates fast — under furniture, along baseboards, woven into upholstery — and an ordinary once-over never gets it all.',
    careNotes: 'Our Rancho Rialto visits lean hard on thorough vacuuming, edge work along the baseboards, and wiping the surfaces where dander settles. We are comfortable working around dogs and cats, and we will follow whatever routine keeps your animal relaxed while we are there.',
    latitude: 32.62, longitude: -114.61 },
  { slug: 'riverfront-rv-park', name: 'Riverfront RV Park', type: 'rv-park', city: 'Yuma', description: 'Colorado River RV park.', audience: 'Waterfront RV seekers.',
    intro: 'Riverfront RV Park sits by the Colorado, but the water coming out of the tap is the same mineral-heavy stuff as everywhere in Yuma — and it stamps white scale onto every fixture it touches. In a small bathroom there is nowhere for that buildup to hide.',
    careNotes: 'Faucets, showerheads, and glass at Riverfront get descaled properly on our first visit, then maintained so the deposits never re-establish. Catch mineral buildup early and it wipes away; let it sit a season and it has to be dissolved off.',
    latitude: 32.74, longitude: -114.68 },
  { slug: 'rocking-k-rv-park', name: 'RocKing K RV Park', type: 'rv-park', city: 'Yuma', description: 'Relaxed-pace RV park.', audience: 'Relaxation-focused RVers.',
    intro: 'Not everyone needs a cleaner every other week, and we will tell you so. Plenty of RocKing K RV Park homes do beautifully on a once-a-month visit — tidy habits plus a modest floor plan means less to keep up with, and we would rather right-size the service than oversell it.',
    careNotes: 'A monthly appointment at RocKing K covers the full home each time rather than rotating rooms, since small footprints let us do it all in one go. Step up the frequency any month you have more going on; drop back down when things quiet again.',
    latitude: 32.70, longitude: -114.61 },
  { slug: 'southern-mesa-rv-park', name: 'Southern Mesa RV Park', type: 'rv-park', city: 'Yuma', description: 'South mesa RV park.', audience: 'Value-conscious RVers.',
    intro: 'Watching the budget does not mean skipping the cleaning — it means paying for exactly what your home needs and nothing more. Southern Mesa RV Park units are small enough that our lowest rates apply, and we quote the number before you commit to anything.',
    careNotes: 'There are no upsells built into a Southern Mesa visit: the price covers the whole checklist, and anything extra is something you asked for by name. On a fixed retirement income, knowing the exact cost every single time is half the point.',
    latitude: 32.65, longitude: -114.61 },
  { slug: 'suni-sands-rv-resort', name: 'Suni Sands RV Resort', type: 'rv-park', city: 'Yuma', description: 'Sunny sands RV resort.', audience: 'Beach-loving RVers.',
    intro: 'Open a Suni Sands RV Resort unit in October after it sat shut all summer and you can taste the dust in the air before you see it. Months of undisturbed settling leaves a film on everything from the countertops to the inside of cabinets that stayed closed the whole time.',
    careNotes: 'We work these Suni Sands reopenings top-down — ceiling first, floors last — so nothing gets cleaned twice and nothing gets missed. Owners who also booked a lock-up clean back in spring consistently find the fall job faster and cheaper.',
    latitude: 32.68, longitude: -114.60 },
  { slug: 'the-palms-rv-resort', name: 'The Palms RV Resort', type: 'rv-park', city: 'Yuma', description: '453-lot 55+ resort with Villas, Casitas, and RV spaces.', audience: 'Active senior RVers.',
    intro: 'Across its 453 lots, The Palms RV Resort spans villas, casitas, and RV spaces — three genuinely different cleaning jobs under one entrance sign. A villa cleans like a small house, a casita like a studio, and an RV like neither, so we scope each quote to what is actually parked or built on your lot.',
    careNotes: 'Casita owners at The Palms are our steadiest bookings: enough real fixtures and finishes to justify professional care, but a footprint that keeps every visit brief and inexpensive. Villas here typically run the same recurring plans our full-size residential clients use.',
    latitude: 32.64, longitude: -114.63 },
  { slug: 'villa-alameda-rv-resort', name: 'Villa Alameda RV Resort', type: 'rv-park', city: 'Yuma', description: 'Villa-style RV resort.', audience: 'Luxury RV travelers.',
    intro: 'Hosting season hits Villa Alameda RV Resort every winter — friends caravan through, family schedules trips around the warm months, and suddenly your home is the destination. We handle the before and after: a company-ready clean ahead of the visit, and a recovery clean once the last guest pulls away.',
    careNotes: 'Villa Alameda hosting cleans put extra time into guest bathrooms, bedding areas, and the kitchen that is about to work overtime. Book the pair — before and after — and the second visit is the one you will be most grateful for.',
    latitude: 32.70, longitude: -114.61 },
  { slug: 'westwind-rv-golf-resort', name: 'Westwind RV & Golf Resort', type: 'rv-park', city: 'Yuma', description: 'Golf RV resort.', audience: 'Golfing RV enthusiasts.',
    intro: 'At Westwind RV & Golf Resort the calendar fills itself — rounds, leagues, dinners at the clubhouse — and housework is what gets squeezed out. That squeeze is our whole business case here: we take the one recurring obligation nobody moved to Yuma for.',
    careNotes: 'Westwind clients usually give us a standing window on a day they are reliably on the course, and the house is done before the back nine is. If a tournament or event shuffles your week, a quick call moves the visit with it.',
    latitude: 32.70, longitude: -114.62 },
  { slug: 'yuma-lakes-rv-resort', name: 'Yuma Lakes RV Resort', type: 'rv-park', city: 'Yuma', description: 'Lake-view RV resort.', audience: 'Water-activity RVers.',
    intro: 'Bookends are what we mostly provide at Yuma Lakes RV Resort: a thorough clean when the season opens and another when it closes, with as much or as little in between as each owner wants. Some clients only ever use those two visits, and that arrangement suits us fine.',
    careNotes: 'The opening clean at Yuma Lakes strips away the summer\'s accumulation; the closing one protects the unit for the months it will sit unattended. Owners who add even one mid-winter visit between the two tell us the whole season feels easier to keep up with.',
    latitude: 32.72, longitude: -114.61 },

  // Mobile Home / Family Parks
  { slug: 'buckeye-trails-mhp', name: 'Buckeye Trails Mobile Home & RV Park', type: 'family-park', city: 'Yuma', description: 'Trails-themed mixed-use community.', audience: 'Families and RV owners.',
    intro: 'Buckeye Trails mixes mobile homes and RVs, and we clean both. A manufactured home here gets our standard residential service at a flat rate sized to its square footage, while rigs parked for the season get the tighter, cabinet-by-cabinet treatment an RV interior calls for.',
    careNotes: 'Unpaved stretches around the park mean grit rides in on every pair of shoes, so we hit entry mats, thresholds, and door tracks first. Skirted homes here also collect dust along the lower window channels, which we vacuum out before wiping.',
    latitude: 32.70, longitude: -114.62 },
  { slug: 'chaparral-mhp', name: 'Chaparral Mobile Home Park', type: 'family-park', city: 'Yuma', description: 'Desert shrub manufactured housing community.', audience: 'Affordable living seekers.',
    intro: 'A single-wide at Chaparral cleans top to bottom in one visit, and our flat rate reflects that smaller footprint. You pay for the home you actually have, not some averaged-out suburban price.',
    careNotes: 'Open desert borders this park, and monsoon gusts push fine sediment through every gap a screen door leaves. Our crews work the window sills and floor edges where that layer settles thickest.',
    latitude: 32.68, longitude: -114.60 },
  { slug: 'country-breeze-mhp', name: 'Country Breeze Mobile Home Park', type: 'family-park', city: 'Yuma', description: 'Breeze-filled mobile home park.', audience: 'Budget-conscious families.',
    intro: 'Families at Country Breeze mostly book us on a bi-weekly rotation, timed for school hours so the house is done before anyone gets home. Recurring visits also cost less per clean than calling us once a year for a rescue job.',
    careNotes: 'The breeze this park is named for carries dust with it, and it finds the same spots every time: ceiling fan blades, blind slats, and the tops of door frames. We wipe all three on every scheduled visit, not just the deep cleans.',
    latitude: 32.69, longitude: -114.64 },
  { slug: 'coyote-ranch-mhc', name: 'Coyote Ranch Manufactured Home Community', type: 'family-park', city: 'Yuma', description: 'Western-themed manufactured housing community.', audience: 'Western-living families.',
    intro: 'When a rental at Coyote Ranch turns over, the landlord walkthrough decides whether the deposit comes back. Our move-out cleans are built around that inspection: oven, range hood, tub surround, baseboards, and the inside of every cabinet.',
    careNotes: 'Manufactured-home fixtures show Yuma\'s hard water fast, and mineral spotting on a faucet reads as neglect to a property manager even when it isn\'t. We descale chrome and glass so the bathroom photographs clean.',
    latitude: 32.70, longitude: -114.61 },
  { slug: 'desert-palms-mobile-estates', name: 'Desert Palms Mobile Estates', type: 'family-park', city: 'Yuma', description: 'Palm-shaded mobile home estates.', audience: 'Families seeking tropical charm.',
    intro: 'Sometimes a home just needs a reset, and that\'s what our deep clean does for residents of Desert Palms Mobile Estates. We degrease the kitchen, scrub the showers back to their original finish, and pull the dust out of vents and corners that weekly tidying never reaches.',
    careNotes: 'Palm trees drop more than shade — fronds and seed litter track indoors and grind into carpet near doorways. Our vacuuming pattern starts at the entries and works inward for exactly that reason.',
    latitude: 32.69, longitude: -114.61 },
  { slug: 'el-prado-estates', name: 'El Prado Estates', type: 'family-park', city: 'Yuma', description: 'Established mobile home estates.', audience: 'Families seeking affordable estates.',
    intro: 'El Prado Estates has been around long enough that many homes here have decades of living in them, and older manufactured homes reward careful cleaning. We know which surfaces take a scrub and which take a gentle hand — vintage paneling and original laminate get treated accordingly.',
    careNotes: 'Established parks tend to have established landscaping, but bare desert soil still surrounds most lots, so the dust load is real. Twice a visit isn\'t too often to run a microfiber over the horizontal surfaces near windows.',
    latitude: 32.69, longitude: -114.63 },
  { slug: 'foothills-mobile-estates', name: 'Foothills Mobile Estates', type: 'family-park', city: 'Yuma', description: 'Elevated mobile home estates.', audience: 'Families seeking foothills views.',
    intro: 'Out at Foothills Mobile Estates, a monthly visit from our crew keeps a home comfortably ahead of the desert. Monthly works well for smaller households: enough frequency to stop buildup, without paying for cleaning you don\'t need.',
    careNotes: 'Wind coming off open ground east of town hits this area with little in the way, so we give extra attention to sliding-door tracks and screen frames. Those channels clog with grit faster here than almost anywhere else we service.',
    latitude: 32.68, longitude: -114.62 },
  { slug: 'glenaire-mh-rv-park', name: 'Glenaire Mobile Home & RV Park', type: 'family-park', city: 'Yuma', description: 'Mixed mobile home and RV community.', audience: 'Mixed-tenure families.',
    intro: 'Because Glenaire houses mobile homes and RVs side by side, our crews arrive ready for either job. The manufactured homes get full residential service; the rigs get the compact-galley, wet-bath approach that fifth wheels and motorhomes actually require.',
    careNotes: 'Neighbors pulling rigs in and out keeps dust airborne more often than in a homes-only park, so exterior-facing surfaces need attention every visit. We wipe down window ledges and clear the entry steps of grit before we ever touch the interior.',
    latitude: 32.70, longitude: -114.61 },
  { slug: 'lazy-k', name: 'Lazy K', type: 'family-park', city: 'Yuma', description: 'Relaxed ranch-style community.', audience: 'Laid-back families.',
    intro: 'Hosting family this weekend? A one-time clean is our most-booked service at Lazy K — one afternoon and the whole place is guest-ready, bathrooms shining and kitchen degreased, with nothing on your plate but the cooking.',
    careNotes: 'Guests notice bathrooms first, so ours get the longest share of the visit: hard-water film off the shower glass, faucets polished, grout brushed. The rest of a compact home falls into place quickly once the wet rooms are done.',
    latitude: 32.71, longitude: -114.61 },
  { slug: 'marble-manor', name: 'Marble Manor', type: 'family-park', city: 'Yuma', description: 'Established mobile home manor community.', audience: 'Families seeking a quality manufactured home community.',
    intro: 'Homes at Marble Manor are kept with pride, and our job is to protect that standard between your own efforts. A crew of two typically finishes a home here in a single appointment — small footprints let us be thorough rather than rushed.',
    careNotes: 'Well-maintained homes still fight Yuma\'s water. Calcium crust creeps onto showerheads and around drain rings no matter how often you wipe, and dissolving it properly is a chemistry job we bring the right products for.',
    latitude: 32.70, longitude: -114.62 },
  { slug: 'melody-mobile-court', name: 'Melody Mobile Court', type: 'family-park', city: 'Yuma', description: 'Established mobile home court.', audience: 'Families seeking community living.',
    intro: 'For working households at Melody Mobile Court, we schedule around the realities of shift work and school pickup — early slots, specific weekdays, whatever keeps the service invisible to your routine. Most clients here settle into an every-other-week rhythm.',
    careNotes: 'Court layouts put homes close together, which means shared driveways and shared dust. Entry rugs, threshold plates, and the first six feet of flooring inside the door take the brunt, and that\'s where our crews concentrate.',
    latitude: 32.72, longitude: -114.63 },
  { slug: 'mountain-cactus-ranch', name: 'Mountain Cactus Ranch', type: 'family-park', city: 'Yuma', description: 'Mountain-view ranch community.', audience: 'Ranch lifestyle enthusiasts.',
    intro: 'The views from Mountain Cactus Ranch come courtesy of open desert, and open desert sends dust straight back. We build our cleans here around that trade-off, treating dust control as the main event rather than an afterthought.',
    careNotes: 'After a monsoon blow-through, the film on furniture and floors can look like a month of neglect happened overnight. A post-storm visit resets everything, and plenty of residents keep us on call for exactly that.',
    latitude: 32.67, longitude: -114.59 },
  { slug: 'shady-acres-mhc', name: 'Shady Acres Manufactured Home and RV Community', type: 'family-park', city: 'Yuma', description: 'Tree-shaded manufactured home community.', audience: 'Mixed-living families.',
    intro: 'Tree cover makes Shady Acres one of the cooler parks in town, and it changes what our crews find inside: less baked-on dust, more leaf litter and pollen at the doors. Whether you\'re in a manufactured home or an RV on a long-term space, we clean to the dwelling in front of us.',
    careNotes: 'Shade helps, but it doesn\'t stop hard water — every fixture in Yuma spots the same way. Kitchens and baths in a smaller home concentrate the buildup into fewer square feet, which lets us address every affected surface in one pass.',
    latitude: 32.69, longitude: -114.61 },
  { slug: 'sierra-pacific', name: 'Sierra Pacific', type: 'family-park', city: 'Yuma', description: 'Family-oriented manufactured housing community with 272 home sites since 1985.', audience: 'Families seeking affordable manufactured home living.',
    intro: 'Sierra Pacific\'s 272 home sites have housed Yuma families since 1985, and homes of that generation carry textures — popcorn ceilings, older vinyl, original tub surrounds — that need the right technique, not just more elbow grease. Our crews have cleaned enough of them to know the difference.',
    careNotes: 'A family home works harder than a snowbird home: more meals cooked, more laundry, more traffic on the floors. Bi-weekly service is what we usually recommend for households at that pace, and the flat rate on a manufactured home keeps it sustainable.',
    latitude: 32.67, longitude: -114.51 },
  { slug: 'westward-village', name: 'Westward Village', type: 'family-park', city: 'Yuma', description: 'Western-themed manufactured home village.', audience: 'Western-loving families.',
    intro: 'Move-out day at Westward Village goes smoother when the cleaning isn\'t on you. We take rentals down to landlord-ready in one appointment — appliances inside and out, floors edge to edge, every drawer emptied of crumbs and dust.',
    careNotes: 'On the west side of town the afternoon wind arrives loaded, and window tracks in this village fill with sand faster than most people expect. Clearing those channels is a standing item on our checklist here, right alongside the door sweeps.',
    latitude: 32.69, longitude: -114.67 },
];

export function getNeighborhoodBySlug(slug: string): Neighborhood | undefined {
  return NEIGHBORHOODS.find((n) => n.slug === slug);
}

export function getNeighborhoodsByType(type: 'neighborhood' | 'rv-park' | 'family-park'): Neighborhood[] {
  return NEIGHBORHOODS.filter((n) => n.type === type);
}

export function getNeighborhoodsByCity(city: string): Neighborhood[] {
  return NEIGHBORHOODS.filter((n) => n.city === city);
}
